# Generated by Django 5.0.8 on 2026-02-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
