# Generated by Django 5.0.8 on 2026-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system_management', '0005_user_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firm', 'role'], name='system_mana_firm_id_d0a627_idx'),
        ),
    ]
