# Generated by Django 5.0.8 on 2026-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0006_user_system_mana_firm_id_d0a627_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firm',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
    ]
