# Generated by Django 5.0.8 on 2026-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0007_firm_is_onboarded_firm_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='max_users',
            field=models.IntegerField(default=4),
        ),
    ]
