# Generated by Django 5.0.8 on 2026-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0008_alter_firm_max_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='model_type',
            field=models.CharField(choices=[('case', 'Case'), ('document', 'Document'), ('user', 'User'), ('firm', 'Firm'), ('note', 'Note')], max_length=50),
        ),
    ]
