# Generated by Django 5.0.8 on 2026-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0009_alter_auditlog_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='data_region',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('SA', 'South Africa'), ('US', 'United States'), ('IN', 'India'), ('PK', 'Pakistan')], default='SA', help_text='Data residency region for this firm. Determines storage location.', max_length=10),
        ),
    ]
