# Generated by Django 5.0.8 on 2026-07-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='firm',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
