"""
Django settings for clearwave project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from decouple import config
# import dj_database_url
from celery.schedules import crontab


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'system_management',
    'case_management',
    'document_management',
    'client_management',
    'forms_engine_management',
    'django_celery_beat',
]

# 

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'system_management.middleware.TenantFilterMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",

]


ROOT_URLCONF = 'clearwave.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         # 'rest_framework.authentication.TokenAuthentication',
        
#         'rest_framework.authentication.TokenAuthentication',  # ← Must have this
#         'rest_framework.authentication.SessionAuthentication',
    
#     ),
#     'EXPIRY_MINUTES': 30,  # Token will expire after 30 minutes

#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',

#         # 'rest_framework.permissions.IsAuthenticated',
#     ),
# }

# REST_FRAMEWORK = {
#     'DEFAULT_THROTTLE_CLASSES': [
#         'rest_framework.throttling.AnonRateThrottle',
#         'rest_framework.throttling.UserRateThrottle',
#     ],
#     'DEFAULT_THROTTLE_RATES': {
#         'anon': '5/min',
#         'user': '30/min',
#         'magic_link': '3/min',
#         'login': '5/min',
#     }
# }
REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),

    # Permissions
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Token Expiry
    'EXPIRY_MINUTES': 30,

    # Throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/min',      # bump this up during testing
        'user': '30/min',
        'magic_link': '3/min',
        'login': '5/min',
    }
}

WSGI_APPLICATION = 'clearwave.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     "default": dj_database_url.config(
#         default=os.environ.get("DATABASE_URL")
#     )
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True
TIME_ZONE = 'UTC'  # or 'Africa/Johannesburg' etc.
# TIME_ZONE = 'UTC'

# USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'system_management.User'
# X_FRAME_OPTIONS = 'ALLOWALL'




# CORS Settings - More permissive for debugging
CORS_ALLOW_ALL_ORIGINS = False  # Temporarily set to True for debugging
CORS_ALLOW_CREDENTIALS = True

# Alternative: Specific origins (use this after debugging)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


CORS_ALLOW_CREDENTIALS = True

# CSRF_TRUSTED_ORIGINS = ['https://6820-102-38-124-42.ngrok-free.app']
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',

]
    # https://d4e3-102-38-124-42.ngrok-free.app 

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
# ALLOWED_HOSTS = [
#     ".railway.app",
#     "localhost",
#     "127.0.0.1",
# ]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS preflight max age
CORS_PREFLIGHT_MAX_AGE = 86400

# CSRF Settings
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False  # Must be False for JS access
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_USE_SESSIONS = False


# Session settings
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
FRONTEND_URL = "http://localhost:3000"

# BACKBLAZE
BACK_BLAZE_KEY_ID = config('BACK_BLAZE_KEY_ID')
BACK_BLAZE_KEY_NAME = config('BACK_BLAZE_KEY_NAME')
BACK_BLAZE_BUCKET_NAME = config('BACK_BLAZE_BUCKET_NAME')

BACK_BLAZE_APLLICATION_KEY =config('BACK_BLAZE_APLLICATION_KEY')

BACKBLAZE_ENDPOINT_URL = config('BACKBLAZE_ENDPOINT_URL')
# GROQ_AI_API_KEY = config('GROQ_AI_API_KEY')

# SENDGRID_API_KEY = config("SENDGRID_API_KEY")

# DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# ── Email — Gmail SMTP ──────────────────────────────────────────
EMAIL_BACKEND        = config('EMAIL_BACKEND')
EMAIL_HOST           = config('EMAIL_HOST')
EMAIL_PORT           = config('EMAIL_PORT')
EMAIL_USE_TLS        = config('EMAIL_USE_TLS')
EMAIL_HOST_USER      = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD  = config('EMAIL_HOST_PASSWORD')  # App Password, not Gmail password
DEFAULT_FROM_EMAIL   = config('EMAIL_HOST_USER')



PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
# PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')

# FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

PAYSTACK_PLANS = {
    'solo': 'PLN_9rjy97c49c8zf55',
    'small_firm': 'PLN_yhxalsh2cyeykty',
    'growing_firm': 'PLN_4cuezzvcrlt5fyl',
}


REDIS_URL = config('REDIS_URL')

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Johannesburg'

# Beat schedule — runs daily at 8AM Joburg time
CELERY_BEAT_SCHEDULE = {
    'send-deadline-reminders': {
        'task': 'case_management.tasks.send_deadline_reminders',
        'schedule': crontab(hour=8, minute=0),
    },
}



CELERY_REDIS_BACKEND_USE_SSL = {
    'ssl_cert_reqs': 'CERT_NONE'
}

CELERY_BROKER_USE_SSL = {
    'ssl_cert_reqs': 'CERT_NONE'
}