# Generated by Django 5.0.8 on 2026-03-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclink',
            name='token',
        ),
        migrations.AddField(
            model_name='magiclink',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
