# Generated by Django 5.0.8 on 2026-03-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_remove_magiclink_token_magiclink_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclink',
            name='token_hash',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
