# Generated by Django 5.0.8 on 2026-02-14 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0001_initial'),
        ('system_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_lawyer',
            field=models.ForeignKey(limit_choices_to={'role__in': ['lawyer', 'firm_owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='system_management.firm'),
        ),
        migrations.AddField(
            model_name='note',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case_management.case'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'status'], name='case_manage_firm_id_e2004a_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_lawyer', 'status'], name='case_manage_assigne_09760b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['deadline'], name='case_manage_deadlin_2fcd32_idx'),
        ),
    ]
