# Generated by Django 5.0.8 on 2026-02-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_initial'),
        ('system_management', '0005_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_types', to='system_management.firm')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('firm', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='matter_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_management.casetype'),
        ),
    ]
