# Generated by Django 5.0.8 on 2026-02-22 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_casetype_alter_case_matter_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
