# Generated by Django 5.0.8 on 2026-02-23 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_case_assigned_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='external_case_number',
            field=models.CharField(blank=True, help_text='Official court/registry/client-provided case number (if applicable)', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Internal system-generated reference (e.g. 2026-ALPHA-0001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
