# Generated by Django 5.0.8 on 2026-02-24 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0005_case_created_by_case_external_case_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned_lawyer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lawyer', 'firm_owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
