# Generated by Django 5.0.8 on 2026-05-31 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_alter_case_assigned_lawyer'),
        ('system_management', '0011_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, help_text='Hours — e.g. 1.5 for 1 hour 30 minutes', max_digits=5)),
                ('activity_type', models.CharField(choices=[('research', 'Research'), ('drafting', 'Drafting'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('court', 'Court Appearance'), ('review', 'Document Review'), ('correspondence', 'Correspondence'), ('filing', 'Filing'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(help_text='What was done during this time.')),
                ('is_billable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='case_management.case')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='system_management.firm')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
