# Generated by Django 5.0.8 on 2026-07-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0007_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='billing_status',
            field=models.CharField(choices=[('not_billed', 'Not Billed'), ('partially_billed', 'Partially Billed'), ('fully_billed', 'Fully Billed')], default='not_billed', max_length=20),
        ),
    ]
