# Generated by Django 5.0.8 on 2026-05-15 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0006_alter_case_assigned_lawyer'),
        ('document_management', '0001_initial'),
        ('system_management', '0009_alter_auditlog_model_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline for the client to complete this form.', null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text="Lawyer's notes when approving or rejecting a submission.", null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forms', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='case_management.case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_form_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False, help_text='False = draft/partial save. True = client clicked Submit.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='forms_engine_management.caseformassignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('case_type', models.ForeignKey(blank=True, help_text='If set, this template is suggested when a case of this type is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='case_management.casetype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_templates', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='system_management.firm')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('firm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_engine_management.formtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.AddField(
            model_name='caseformassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to='forms_engine_management.formtemplate'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text shown to the client.')),
                ('input_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text Area'), ('number', 'Number Input'), ('date', 'Date Picker'), ('email', 'Email Input'), ('select', 'Dropdown Selection'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('yes_no', 'Yes / No')], max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_other_option', models.BooleanField(default=False, help_text="Adds an 'Other (please specify)' option for select/checkbox types.")),
                ('helper_text', models.CharField(blank=True, help_text='Optional hint shown below the question field.', max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='system_management.firm')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine_management.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='caseformassignment',
            unique_together={('case', 'template')},
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_number', models.FloatField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_boolean', models.BooleanField(blank=True, null=True)),
                ('other_text', models.CharField(blank=True, help_text="Free text when client selects 'Other' on a select/checkbox question.", max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, help_text='For file-type questions, reference the document uploaded via document_management.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to='document_management.document')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_engine_management.formsection')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_engine_management.formsubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_engine_management.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='forms_engine_management.questionoption')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required_override', models.BooleanField(blank=True, help_text="If set, overrides the question's default is_required. Leave blank to use question default.", null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='forms_engine_management.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='forms_engine_management.formsection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('section', 'question')},
            },
        ),
    ]
