# Generated by Django 5.0.8 on 2026-05-18 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
        ('forms_engine_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Client's WhatsApp number in E.164 format e.g. +27821234567", max_length=20)),
                ('current_section_index', models.PositiveIntegerField(default=0, help_text='Index of the section currently being answered (0-based).')),
                ('current_question_index', models.PositiveIntegerField(default=0, help_text='Index of the question within the current section (0-based).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='active', max_length=20)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('meta', 'Meta Cloud API'), ('threesixty', '360dialog')], default='twilio', max_length=20)),
                ('provider_conversation_id', models.CharField(blank=True, help_text='Twilio SID, Meta WABA thread ID, etc. Used to thread replies.', max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Updated on every inbound or outbound message.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='How many times the last message was resent after no reply.')),
                ('last_error', models.TextField(blank=True, help_text='Last webhook or delivery error, for debugging.', null=True)),
                ('assignment', models.ForeignKey(help_text='The form assignment this session is completing.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='forms_engine_management.caseformassignment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, help_text='Created when bot starts. Null until first message received.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to='forms_engine_management.formsubmission')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('assignment', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('system', 'System')], default='text', max_length=10)),
                ('body', models.TextField(blank=True, help_text='Text content of the message.', null=True)),
                ('provider_message_id', models.CharField(blank=True, help_text='Twilio MessageSid, Meta message_id etc.', max_length=255, null=True)),
                ('delivered', models.BooleanField(default=False, help_text='Outbound only — confirmed delivered by provider webhook.')),
                ('read', models.BooleanField(default=False, help_text='Outbound only — confirmed read by client (WhatsApp blue ticks).')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, help_text='If the client sent a file, it lands in document_management and is linked here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='document_management.document')),
                ('question', models.ForeignKey(blank=True, help_text='Which question this inbound message was answering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='forms_engine_management.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forms_engine_management.whatsappsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
